import { IMessageRepository } from '../../domain/repositories/IMessageRepository';
import { IMessageSchedulerService } from '../services/IMessageSchedulerService';
import { ScheduledMessage, MessagePlatform } from '../../domain/models/ScheduledMessage';

export interface ScheduleMessageDTO {
    userId: string;
    content: string;
    recipientId: string;
    recipientName?: string;
    sendAt: Date;
    platform?: MessagePlatform;
    recurrence?: string;
    imageUrl?: string;
}

export class ScheduleMessageUseCase {
    constructor(
        private readonly messageRepository: IMessageRepository,
        private readonly messageScheduler: IMessageSchedulerService
    ) {}

    async execute(dto: ScheduleMessageDTO): Promise<ScheduledMessage> {
        if (!dto.content || dto.content.trim() === '') {
            throw new Error("Message content cannot be empty");
        }
        if (!dto.recipientId || dto.recipientId.trim() === '') {
            throw new Error("Recipient ID is required");
        }
        const toleranceMs = 5 * 60 * 1000; // 5 minutos de tolerância para dessincronia de relógio do cliente
        if (dto.sendAt.getTime() < Date.now() - toleranceMs) {
            throw new Error("Send date must be in the future");
        }
        if (!dto.userId) {
            throw new Error("User ID is required");
        }

        const message = new ScheduledMessage(
            null, // Generated by database
            dto.userId,
            dto.content,
            dto.recipientId,
            dto.sendAt,
            'pending',
            dto.platform || 'whatsapp',
            new Date(),
            { recurrence: dto.recurrence, imageUrl: dto.imageUrl, recipientName: dto.recipientName },
            dto.recipientName || null
        );
        console.log("Saving message with metadata:", message.metadata);

        // 1. Salvar evento no Banco de Dados Confiavel (PostgreSQL)
        const savedMessage = await this.messageRepository.save(message);
        console.log("Saved message has metadata:", savedMessage.metadata);


        // 2. Calcula qual será o delay em milissegundos
        const targetTimeMs = dto.sendAt.getTime();
        const currentTimeMs = Date.now();
        const delayMs = Math.max(0, targetTimeMs - currentTimeMs); // Sempre > 0
        
        // 3. Adiciona na Fila (BullMQ/Redis) com esse atraso
        await this.messageScheduler.schedule(savedMessage, delayMs);

        return savedMessage;
    }
}
